webtalk_init -webtalk_dir /home/nikhil/git_clones/AWS/aws-fpga/hdk/cl/examples/cl_dram_dma/verif/sim/vivado/test_dram_dma_retention_c/xsim.dir/tb/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 17 20:04:09 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211916151_0_0_263" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f0ba1d4c-32fa-4cd3-9a29-95314403c332" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7e2b7e57-aac3-4a02-8a66-ef579c942eff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04 LTS (beaver-three-eyed-raven X92)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3522.491 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "198" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "18974 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "10308 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "197924" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "18911" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "77.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "2838828_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2603664898 -regid "211916151_0_0_263" -xml /home/nikhil/git_clones/AWS/aws-fpga/hdk/cl/examples/cl_dram_dma/verif/sim/vivado/test_dram_dma_retention_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.xml -html /home/nikhil/git_clones/AWS/aws-fpga/hdk/cl/examples/cl_dram_dma/verif/sim/vivado/test_dram_dma_retention_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.html -wdm /home/nikhil/git_clones/AWS/aws-fpga/hdk/cl/examples/cl_dram_dma/verif/sim/vivado/test_dram_dma_retention_c/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
