//
// Generated by Bluespec Compiler, version 2019.05.beta2 (build a88bf40db, 2019-05-24)
//
//
//
//
// Ports:
// Name                         I/O  size props
// RDY_reset                      O     1 const
// RDY_predict_req                O     1
// predict_rsp                    O    64
// RDY_bp_train                   O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// predict_req_pc                 I    64 reg
// predict_rsp_is_i32_not_i16     I     1
// predict_rsp_instr              I    32
// bp_train_pc                    I    64
// bp_train_is_i32_not_i16        I     1
// bp_train_instr                 I    32
// bp_train_cf_info               I   195
// EN_reset                       I     1
// EN_predict_req                 I     1
// EN_bp_train                    I     1
//
// Combinational paths from inputs to outputs:
//   (predict_rsp_is_i32_not_i16, predict_rsp_instr) -> predict_rsp
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBranch_Predictor(CLK,
			  RST_N,

			  EN_reset,
			  RDY_reset,

			  predict_req_pc,
			  EN_predict_req,
			  RDY_predict_req,

			  predict_rsp_is_i32_not_i16,
			  predict_rsp_instr,
			  predict_rsp,

			  bp_train_pc,
			  bp_train_is_i32_not_i16,
			  bp_train_instr,
			  bp_train_cf_info,
			  EN_bp_train,
			  RDY_bp_train);
  input  CLK;
  input  RST_N;

  // action method reset
  input  EN_reset;
  output RDY_reset;

  // action method predict_req
  input  [63 : 0] predict_req_pc;
  input  EN_predict_req;
  output RDY_predict_req;

  // value method predict_rsp
  input  predict_rsp_is_i32_not_i16;
  input  [31 : 0] predict_rsp_instr;
  output [63 : 0] predict_rsp;

  // action method bp_train
  input  [63 : 0] bp_train_pc;
  input  bp_train_is_i32_not_i16;
  input  [31 : 0] bp_train_instr;
  input  [194 : 0] bp_train_cf_info;
  input  EN_bp_train;
  output RDY_bp_train;

  // signals for module outputs
  wire [63 : 0] predict_rsp;
  wire RDY_bp_train, RDY_predict_req, RDY_reset;

  // register rg_index
  reg [8 : 0] rg_index;
  wire [8 : 0] rg_index$D_IN;
  wire rg_index$EN;

  // register rg_pc
  reg [63 : 0] rg_pc;
  wire [63 : 0] rg_pc$D_IN;
  wire rg_pc$EN;

  // register rg_ras
  reg [1039 : 0] rg_ras;
  wire [1039 : 0] rg_ras$D_IN;
  wire rg_ras$EN;

  // register rg_resetting
  reg rg_resetting;
  wire rg_resetting$D_IN, rg_resetting$EN;

  // ports of submodule btb_bramcore2
  wire [117 : 0] btb_bramcore2$DIA, btb_bramcore2$DIB, btb_bramcore2$DOA;
  wire [8 : 0] btb_bramcore2$ADDRA, btb_bramcore2$ADDRB;
  wire btb_bramcore2$ENA,
       btb_bramcore2$ENB,
       btb_bramcore2$WEA,
       btb_bramcore2$WEB;

  // ports of submodule rf_btb_fsms
  wire [8 : 0] rf_btb_fsms$ADDR_1,
	       rf_btb_fsms$ADDR_2,
	       rf_btb_fsms$ADDR_3,
	       rf_btb_fsms$ADDR_4,
	       rf_btb_fsms$ADDR_5,
	       rf_btb_fsms$ADDR_IN;
  wire [1 : 0] rf_btb_fsms$D_IN, rf_btb_fsms$D_OUT_1;
  wire rf_btb_fsms$WE;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_reset,
       CAN_FIRE_bp_train,
       CAN_FIRE_predict_req,
       CAN_FIRE_reset,
       WILL_FIRE_RL_rl_reset,
       WILL_FIRE_bp_train,
       WILL_FIRE_predict_req,
       WILL_FIRE_reset;

  // inputs to muxes for submodule ports
  reg [1 : 0] MUX_rf_btb_fsms$upd_2__VAL_1;
  wire [117 : 0] MUX_btb_bramcore2$b_put_3__VAL_1;
  wire [8 : 0] MUX_rg_index$write_1__VAL_2;
  wire MUX_btb_bramcore2$b_put_1__SEL_1;

  // remaining internal signals
  reg [63 : 0] _theResult_____1_fst__h8913;
  reg [1 : 0] _theResult_____1_snd__h8872, _theResult_____1_snd__h8914;
  wire [63 : 0] IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d256,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d266,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d277,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d288,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d299,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d310,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d321,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d332,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d343,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d354,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d365,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d376,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d387,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d398,
		IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d407,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d257,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d267,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d278,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d289,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d300,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d311,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d322,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d333,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d344,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d355,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d366,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d377,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d388,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d399,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d408,
		IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d428,
		IF_bp_train_cf_info_BITS_194_TO_193_EQ_0_THEN__ETC__q1,
		IF_btb_bramcore2_a_read__03_BIT_117_04_AND_btb_ETC___d114,
		_theResult_____1_fst__h8757,
		_theResult_____1_fst__h8871,
		pred_pc___1__h3690,
		pred_pc__h2576,
		ret_pc___1__h4443,
		ret_pc__h4404;
  wire [1 : 0] _theResult_____1_snd_snd__h8759;
  wire IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d224,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d260,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d271,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d282,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d293,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d304,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d315,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d326,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d337,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d348,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d359,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d370,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d381,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d392,
       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d402,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d248,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d261,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d272,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d283,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d294,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d305,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d316,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d327,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d338,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d349,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d360,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d371,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d382,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d393,
       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d403,
       IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d193,
       IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d196,
       IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d217,
       IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d242,
       IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d209,
       IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210,
       IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219,
       IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d245,
       IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d157,
       IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158,
       IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177,
       IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199,
       IF_predict_rsp_is_i32_not_i16_OR_predict_rsp_i_ETC___d79,
       IF_predict_rsp_is_i32_not_i16_OR_predict_rsp_i_ETC___d94,
       IF_predict_rsp_is_i32_not_i16_THEN_NOT_predict_ETC___d50,
       IF_predict_rsp_is_i32_not_i16_THEN_NOT_predict_ETC___d51,
       IF_predict_rsp_is_i32_not_i16_THEN_predict_rsp_ETC___d89,
       IF_predict_rsp_is_i32_not_i16_THEN_predict_rsp_ETC___d97,
       NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d134,
       NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d241,
       NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1001__ETC___d139,
       NOT_bp_train_instr_BITS_6_TO_0_15_EQ_0b1100111_ETC___d233,
       NOT_predict_rsp_instr_BITS_11_TO_7_8_EQ_predic_ETC___d91,
       bp_train_instr_BITS_11_TO_7_25_EQ_bp_train_ins_ETC___d213,
       bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d173,
       bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d216,
       bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_O_ETC___d188,
       bp_train_instr_BITS_15_TO_12_22_EQ_0b1001_35_A_ETC___d153,
       bp_train_instr_BITS_6_TO_0_15_EQ_0b1100111_59__ETC___d170,
       predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d26,
       predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d93,
       predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1001_7__ETC___d30,
       predict_rsp_instr_BITS_6_TO_0_EQ_0b1100111_2_O_ETC___d63;

  // action method reset
  assign RDY_reset = 1'd1 ;
  assign CAN_FIRE_reset = 1'd1 ;
  assign WILL_FIRE_reset = EN_reset ;

  // action method predict_req
  assign RDY_predict_req = !rg_resetting ;
  assign CAN_FIRE_predict_req = !rg_resetting ;
  assign WILL_FIRE_predict_req = EN_predict_req ;

  // value method predict_rsp
  assign predict_rsp =
	     (IF_predict_rsp_is_i32_not_i16_THEN_NOT_predict_ETC___d51 &&
	      IF_predict_rsp_is_i32_not_i16_THEN_predict_rsp_ETC___d97 &&
	      rg_ras[64]) ?
	       rg_ras[63:0] :
	       IF_btb_bramcore2_a_read__03_BIT_117_04_AND_btb_ETC___d114 ;

  // action method bp_train
  assign RDY_bp_train = 1'd1 ;
  assign CAN_FIRE_bp_train = 1'd1 ;
  assign WILL_FIRE_bp_train = EN_bp_train ;

  // submodule btb_bramcore2
  BRAM2 #(.PIPELINED(1'd0),
	  .ADDR_WIDTH(32'd9),
	  .DATA_WIDTH(32'd118),
	  .MEMSIZE(10'd512)) btb_bramcore2(.CLKA(CLK),
					   .CLKB(CLK),
					   .ADDRA(btb_bramcore2$ADDRA),
					   .ADDRB(btb_bramcore2$ADDRB),
					   .DIA(btb_bramcore2$DIA),
					   .DIB(btb_bramcore2$DIB),
					   .WEA(btb_bramcore2$WEA),
					   .WEB(btb_bramcore2$WEB),
					   .ENA(btb_bramcore2$ENA),
					   .ENB(btb_bramcore2$ENB),
					   .DOA(btb_bramcore2$DOA),
					   .DOB());

  // submodule rf_btb_fsms
  RegFile #(.addr_width(32'd9),
	    .data_width(32'd2),
	    .lo(9'h0),
	    .hi(9'd511)) rf_btb_fsms(.CLK(CLK),
				     .ADDR_1(rf_btb_fsms$ADDR_1),
				     .ADDR_2(rf_btb_fsms$ADDR_2),
				     .ADDR_3(rf_btb_fsms$ADDR_3),
				     .ADDR_4(rf_btb_fsms$ADDR_4),
				     .ADDR_5(rf_btb_fsms$ADDR_5),
				     .ADDR_IN(rf_btb_fsms$ADDR_IN),
				     .D_IN(rf_btb_fsms$D_IN),
				     .WE(rf_btb_fsms$WE),
				     .D_OUT_1(rf_btb_fsms$D_OUT_1),
				     .D_OUT_2(),
				     .D_OUT_3(),
				     .D_OUT_4(),
				     .D_OUT_5());

  // rule RL_rl_reset
  assign CAN_FIRE_RL_rl_reset = rg_resetting ;
  assign WILL_FIRE_RL_rl_reset = rg_resetting && !EN_bp_train ;

  // inputs to muxes for submodule ports
  assign MUX_btb_bramcore2$b_put_1__SEL_1 =
	     EN_bp_train &&
	     (bp_train_cf_info[194:193] == 2'd0 ||
	      bp_train_cf_info[194:193] == 2'd1 ||
	      bp_train_cf_info[194:193] == 2'd2) ;
  assign MUX_btb_bramcore2$b_put_3__VAL_1 =
	     { 1'd1,
	       bp_train_cf_info[192:139],
	       IF_bp_train_cf_info_BITS_194_TO_193_EQ_0_THEN__ETC__q1[63:1] } ;
  always@(bp_train_cf_info or
	  rf_btb_fsms$D_OUT_1 or _theResult_____1_snd_snd__h8759)
  begin
    case (bp_train_cf_info[194:193])
      2'd0: MUX_rf_btb_fsms$upd_2__VAL_1 = _theResult_____1_snd_snd__h8759;
      2'd1, 2'd2: MUX_rf_btb_fsms$upd_2__VAL_1 = 2'b11;
      2'd3: MUX_rf_btb_fsms$upd_2__VAL_1 = rf_btb_fsms$D_OUT_1;
    endcase
  end
  assign MUX_rg_index$write_1__VAL_2 = rg_index + 9'd1 ;

  // register rg_index
  assign rg_index$D_IN = EN_reset ? 9'd0 : MUX_rg_index$write_1__VAL_2 ;
  assign rg_index$EN = WILL_FIRE_RL_rl_reset || EN_reset ;

  // register rg_pc
  assign rg_pc$D_IN = predict_req_pc ;
  assign rg_pc$EN = EN_predict_req ;

  // register rg_ras
  assign rg_ras$D_IN =
	     { IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d248,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d257,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d261,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d267,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d272,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d278,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d283,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d289,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d294,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d300,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d305,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d311,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d316,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d322,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d327,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d333,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d338,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d344,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d349,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d355,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d360,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d366,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d371,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d377,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d382,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d388,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d393,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d399,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d403,
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d408,
	       IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	       IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	       IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d157 &&
	       (IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d193 ||
		IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d196) ||
	       ((IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
		 IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
		  rg_ras[129] :
		  rg_ras[64]),
	       IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d428 } ;
  assign rg_ras$EN = EN_bp_train ;

  // register rg_resetting
  assign rg_resetting$D_IN = EN_reset ;
  assign rg_resetting$EN =
	     WILL_FIRE_RL_rl_reset && rg_index == 9'd511 || EN_reset ;

  // submodule btb_bramcore2
  assign btb_bramcore2$ADDRA = predict_req_pc[9:1] ;
  assign btb_bramcore2$ADDRB =
	     MUX_btb_bramcore2$b_put_1__SEL_1 ?
	       bp_train_cf_info[138:130] :
	       rg_index ;
  assign btb_bramcore2$DIA =
	     118'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAA /* unspecified value */  ;
  assign btb_bramcore2$DIB =
	     MUX_btb_bramcore2$b_put_1__SEL_1 ?
	       MUX_btb_bramcore2$b_put_3__VAL_1 :
	       118'd0 ;
  assign btb_bramcore2$WEA = 1'd0 ;
  assign btb_bramcore2$WEB = 1'd1 ;
  assign btb_bramcore2$ENA = EN_predict_req ;
  assign btb_bramcore2$ENB =
	     EN_bp_train &&
	     (bp_train_cf_info[194:193] == 2'd0 ||
	      bp_train_cf_info[194:193] == 2'd1 ||
	      bp_train_cf_info[194:193] == 2'd2) ||
	     WILL_FIRE_RL_rl_reset ;

  // submodule rf_btb_fsms
  assign rf_btb_fsms$ADDR_1 = bp_train_cf_info[138:130] ;
  assign rf_btb_fsms$ADDR_2 = 9'h0 ;
  assign rf_btb_fsms$ADDR_3 = 9'h0 ;
  assign rf_btb_fsms$ADDR_4 = 9'h0 ;
  assign rf_btb_fsms$ADDR_5 = 9'h0 ;
  assign rf_btb_fsms$ADDR_IN =
	     MUX_btb_bramcore2$b_put_1__SEL_1 ?
	       bp_train_cf_info[138:130] :
	       rg_index ;
  assign rf_btb_fsms$D_IN =
	     MUX_btb_bramcore2$b_put_1__SEL_1 ?
	       MUX_rf_btb_fsms$upd_2__VAL_1 :
	       2'b0 ;
  assign rf_btb_fsms$WE =
	     EN_bp_train &&
	     (bp_train_cf_info[194:193] == 2'd0 ||
	      bp_train_cf_info[194:193] == 2'd1 ||
	      bp_train_cf_info[194:193] == 2'd2) ||
	     WILL_FIRE_RL_rl_reset ;

  // remaining internal signals
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d224 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[1039] :
	       rg_ras[974] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d256 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[1038:975] :
	       rg_ras[973:910] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d260 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[974] :
	       rg_ras[909] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d266 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[973:910] :
	       rg_ras[908:845] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d271 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[909] :
	       rg_ras[844] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d277 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[908:845] :
	       rg_ras[843:780] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d282 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[844] :
	       rg_ras[779] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d288 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[843:780] :
	       rg_ras[778:715] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d293 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[779] :
	       rg_ras[714] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d299 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[778:715] :
	       rg_ras[713:650] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d304 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[714] :
	       rg_ras[649] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d310 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[713:650] :
	       rg_ras[648:585] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d315 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[649] :
	       rg_ras[584] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d321 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[648:585] :
	       rg_ras[583:520] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d326 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[584] :
	       rg_ras[519] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d332 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[583:520] :
	       rg_ras[518:455] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d337 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[519] :
	       rg_ras[454] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d343 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[518:455] :
	       rg_ras[453:390] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d348 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[454] :
	       rg_ras[389] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d354 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[453:390] :
	       rg_ras[388:325] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d359 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[389] :
	       rg_ras[324] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d365 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[388:325] :
	       rg_ras[323:260] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d370 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[324] :
	       rg_ras[259] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d376 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[323:260] :
	       rg_ras[258:195] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d381 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[259] :
	       rg_ras[194] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d387 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[258:195] :
	       rg_ras[193:130] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d392 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[194] :
	       rg_ras[129] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d398 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[193:130] :
	       rg_ras[128:65] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d402 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[129] :
	       rg_ras[64] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d407 =
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 &&
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	      IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219) ?
	       rg_ras[128:65] :
	       rg_ras[63:0] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d248 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d224 :
	       IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d245 &&
	       rg_ras[1039] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d257 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d256 :
	       rg_ras[1038:975] ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d261 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d260 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d224 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d267 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d266 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d256 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d272 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d271 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d260 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d278 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d277 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d266 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d283 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d282 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d271 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d289 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d288 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d277 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d294 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d293 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d282 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d300 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d299 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d288 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d305 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d304 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d293 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d311 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d310 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d299 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d316 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d315 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d304 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d322 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d321 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d310 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d327 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d326 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d315 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d333 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d332 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d321 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d338 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d337 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d326 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d344 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d343 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d332 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d349 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d348 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d337 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d355 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d354 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d343 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d360 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d359 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d348 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d366 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d365 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d354 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d371 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d370 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d359 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d377 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d376 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d365 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d382 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d381 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d370 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d388 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d387 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d376 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d393 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d392 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d381 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d399 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d398 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d387 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d403 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d402 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d392 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d408 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d407 :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d398 ;
  assign IF_IF_bp_train_is_i32_not_i16_THEN_bp_train_in_ETC___d428 =
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 ||
	      IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199) ?
	       (bp_train_is_i32_not_i16 ? ret_pc__h4404 : ret_pc___1__h4443) :
	       IF_IF_bp_train_is_i32_not_i16_THEN_NOT_bp_trai_ETC___d407 ;
  assign IF_bp_train_cf_info_BITS_194_TO_193_EQ_0_THEN__ETC__q1 =
	     (bp_train_cf_info[194:193] == 2'd0) ?
	       _theResult_____1_fst__h8757 :
	       bp_train_cf_info[63:0] ;
  assign IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d193 =
	     (bp_train_is_i32_not_i16 ||
	      bp_train_instr[15:13] == 3'b101 &&
	      bp_train_instr[1:0] == 2'b01) ?
	       bp_train_instr[19:15] != 5'd1 &&
	       bp_train_instr[19:15] != 5'd5 :
	       (bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_O_ETC___d188 ?
		  bp_train_instr[11:7] != 5'd1 &&
		  bp_train_instr[11:7] != 5'd5 :
		  bp_train_instr[19:15] != 5'd1 &&
		  bp_train_instr[19:15] != 5'd5) ;
  assign IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d196 =
	     (bp_train_is_i32_not_i16 ||
	      bp_train_instr[15:13] == 3'b101 &&
	      bp_train_instr[1:0] == 2'b01) ?
	       bp_train_instr[19:15] == 5'd1 ||
	       bp_train_instr[19:15] == 5'd5 :
	       (bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_O_ETC___d188 ?
		  bp_train_instr[11:7] == 5'd1 ||
		  bp_train_instr[11:7] == 5'd5 :
		  bp_train_instr[19:15] == 5'd1 ||
		  bp_train_instr[19:15] == 5'd5) ;
  assign IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d217 =
	     (bp_train_is_i32_not_i16 ||
	      bp_train_instr[15:13] == 3'b101 &&
	      bp_train_instr[1:0] == 2'b01) ?
	       !bp_train_instr_BITS_11_TO_7_25_EQ_bp_train_ins_ETC___d213 :
	       bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d216 ;
  assign IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d242 =
	     (bp_train_is_i32_not_i16 ||
	      bp_train_instr[15:13] == 3'b101 &&
	      bp_train_instr[1:0] == 2'b01) ?
	       bp_train_instr_BITS_11_TO_7_25_EQ_bp_train_ins_ETC___d213 :
	       NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d241 ;
  assign IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d209 =
	     bp_train_is_i32_not_i16 ?
	       bp_train_instr[11:7] != 5'd1 && bp_train_instr[11:7] != 5'd5 :
	       bp_train_instr[15:13] == 3'b101 &&
	       bp_train_instr[1:0] == 2'b01 ||
	       bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d173 ||
	       NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1001__ETC___d139 &&
	       bp_train_instr[11:7] != 5'd1 &&
	       bp_train_instr[11:7] != 5'd5 ;
  assign IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d210 =
	     (bp_train_is_i32_not_i16 ?
		bp_train_instr[6:0] != 7'b1101111 :
		(bp_train_instr[15:13] != 3'b101 ||
		 bp_train_instr[1:0] != 2'b01) &&
		(bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d173 ||
		 bp_train_instr_BITS_15_TO_12_22_EQ_0b1001_35_A_ETC___d153 ||
		 bp_train_instr[6:0] != 7'b1101111)) ||
	     IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d209 ;
  assign IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d219 =
	     IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d209 &&
	     IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d196 ||
	     IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d157 &&
	     IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d196 &&
	     IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d217 ;
  assign IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d245 =
	     (bp_train_is_i32_not_i16 ?
		NOT_bp_train_instr_BITS_6_TO_0_15_EQ_0b1100111_ETC___d233 :
		bp_train_instr[15:13] == 3'b101 &&
		bp_train_instr[1:0] == 2'b01 ||
		NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d134 &&
		NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1001__ETC___d139 &&
		NOT_bp_train_instr_BITS_6_TO_0_15_EQ_0b1100111_ETC___d233) ||
	     (IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d157 ||
	      IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d193) &&
	     (IF_bp_train_is_i32_not_i16_THEN_NOT_bp_train_i_ETC___d209 ||
	      IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d193 ||
	      IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d242) ;
  assign IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d157 =
	     bp_train_is_i32_not_i16 ?
	       bp_train_instr[11:7] == 5'd1 || bp_train_instr[11:7] == 5'd5 :
	       (bp_train_instr[15:13] != 3'b101 ||
		bp_train_instr[1:0] != 2'b01) &&
	       NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d134 &&
	       (bp_train_instr_BITS_15_TO_12_22_EQ_0b1001_35_A_ETC___d153 ||
		bp_train_instr[11:7] == 5'd1 ||
		bp_train_instr[11:7] == 5'd5) ;
  assign IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d158 =
	     (bp_train_is_i32_not_i16 ?
		bp_train_instr[6:0] == 7'b1101111 :
		bp_train_instr[15:13] == 3'b101 &&
		bp_train_instr[1:0] == 2'b01 ||
		NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d134 &&
		NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1001__ETC___d139 &&
		bp_train_instr[6:0] == 7'b1101111) &&
	     IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d157 ;
  assign IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 =
	     bp_train_is_i32_not_i16 ?
	       bp_train_instr_BITS_6_TO_0_15_EQ_0b1100111_59__ETC___d170 :
	       (bp_train_instr[15:13] != 3'b101 ||
		bp_train_instr[1:0] != 2'b01) &&
	       (bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d173 ||
		bp_train_instr_BITS_15_TO_12_22_EQ_0b1001_35_A_ETC___d153 ||
		bp_train_instr_BITS_6_TO_0_15_EQ_0b1100111_59__ETC___d170) ;
  assign IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d199 =
	     IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d177 &&
	     IF_bp_train_is_i32_not_i16_THEN_bp_train_instr_ETC___d157 &&
	     (IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d193 ||
	      IF_bp_train_is_i32_not_i16_OR_bp_train_instr_B_ETC___d196) ;
  assign IF_btb_bramcore2_a_read__03_BIT_117_04_AND_btb_ETC___d114 =
	     (btb_bramcore2$DOA[117] &&
	      btb_bramcore2$DOA[116:63] == rg_pc[63:10]) ?
	       pred_pc___1__h3690 :
	       pred_pc__h2576 ;
  assign IF_predict_rsp_is_i32_not_i16_OR_predict_rsp_i_ETC___d79 =
	     (predict_rsp_is_i32_not_i16 ||
	      predict_rsp_instr[15:13] == 3'b101 &&
	      predict_rsp_instr[1:0] == 2'b01) ?
	       predict_rsp_instr[19:15] == 5'd1 ||
	       predict_rsp_instr[19:15] == 5'd5 :
	       (((predict_rsp_instr[15:12] == 4'b1000 ||
		  predict_rsp_instr[15:12] == 4'b1001) &&
		 predict_rsp_instr[11:7] != 5'd0 &&
		 predict_rsp_instr[6:2] == 5'd0 &&
		 predict_rsp_instr[1:0] == 2'b10) ?
		  predict_rsp_instr[11:7] == 5'd1 ||
		  predict_rsp_instr[11:7] == 5'd5 :
		  predict_rsp_instr[19:15] == 5'd1 ||
		  predict_rsp_instr[19:15] == 5'd5) ;
  assign IF_predict_rsp_is_i32_not_i16_OR_predict_rsp_i_ETC___d94 =
	     (predict_rsp_is_i32_not_i16 ||
	      predict_rsp_instr[15:13] == 3'b101 &&
	      predict_rsp_instr[1:0] == 2'b01) ?
	       NOT_predict_rsp_instr_BITS_11_TO_7_8_EQ_predic_ETC___d91 :
	       predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d93 ;
  assign IF_predict_rsp_is_i32_not_i16_THEN_NOT_predict_ETC___d50 =
	     predict_rsp_is_i32_not_i16 ?
	       predict_rsp_instr[11:7] != 5'd1 &&
	       predict_rsp_instr[11:7] != 5'd5 :
	       predict_rsp_instr[15:13] == 3'b101 &&
	       predict_rsp_instr[1:0] == 2'b01 ||
	       predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d26 ||
	       (predict_rsp_instr[15:12] != 4'b1001 ||
		predict_rsp_instr[11:7] == 5'd0 ||
		predict_rsp_instr[6:2] != 5'd0 ||
		predict_rsp_instr[1:0] != 2'b10) &&
	       predict_rsp_instr[11:7] != 5'd1 &&
	       predict_rsp_instr[11:7] != 5'd5 ;
  assign IF_predict_rsp_is_i32_not_i16_THEN_NOT_predict_ETC___d51 =
	     (predict_rsp_is_i32_not_i16 ?
		predict_rsp_instr[6:0] != 7'b1101111 :
		(predict_rsp_instr[15:13] != 3'b101 ||
		 predict_rsp_instr[1:0] != 2'b01) &&
		(predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d26 ||
		 predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1001_7__ETC___d30 ||
		 predict_rsp_instr[6:0] != 7'b1101111)) ||
	     IF_predict_rsp_is_i32_not_i16_THEN_NOT_predict_ETC___d50 ;
  assign IF_predict_rsp_is_i32_not_i16_THEN_predict_rsp_ETC___d89 =
	     (predict_rsp_is_i32_not_i16 ?
		predict_rsp_instr[11:7] == 5'd1 ||
		predict_rsp_instr[11:7] == 5'd5 :
		(predict_rsp_instr[15:13] != 3'b101 ||
		 predict_rsp_instr[1:0] != 2'b01) &&
		(predict_rsp_instr[15:12] != 4'b1000 ||
		 predict_rsp_instr[11:7] == 5'd0 ||
		 predict_rsp_instr[6:2] != 5'd0 ||
		 predict_rsp_instr[1:0] != 2'b10) &&
		(predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1001_7__ETC___d30 ||
		 predict_rsp_instr[11:7] == 5'd1 ||
		 predict_rsp_instr[11:7] == 5'd5)) &&
	     IF_predict_rsp_is_i32_not_i16_OR_predict_rsp_i_ETC___d79 ;
  assign IF_predict_rsp_is_i32_not_i16_THEN_predict_rsp_ETC___d97 =
	     (predict_rsp_is_i32_not_i16 ?
		predict_rsp_instr_BITS_6_TO_0_EQ_0b1100111_2_O_ETC___d63 :
		(predict_rsp_instr[15:13] != 3'b101 ||
		 predict_rsp_instr[1:0] != 2'b01) &&
		(predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d26 ||
		 predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1001_7__ETC___d30 ||
		 predict_rsp_instr_BITS_6_TO_0_EQ_0b1100111_2_O_ETC___d63)) &&
	     (IF_predict_rsp_is_i32_not_i16_THEN_NOT_predict_ETC___d50 &&
	      IF_predict_rsp_is_i32_not_i16_OR_predict_rsp_i_ETC___d79 ||
	      IF_predict_rsp_is_i32_not_i16_THEN_predict_rsp_ETC___d89 &&
	      IF_predict_rsp_is_i32_not_i16_OR_predict_rsp_i_ETC___d94) ;
  assign NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d134 =
	     bp_train_instr[15:12] != 4'b1000 ||
	     bp_train_instr[11:7] == 5'd0 ||
	     bp_train_instr[6:2] != 5'd0 ||
	     bp_train_instr[1:0] != 2'b10 ;
  assign NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d241 =
	     NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1000__ETC___d134 &&
	     (bp_train_instr_BITS_15_TO_12_22_EQ_0b1001_35_A_ETC___d153 ?
		bp_train_instr[11:7] == 5'd1 :
		bp_train_instr_BITS_11_TO_7_25_EQ_bp_train_ins_ETC___d213) ;
  assign NOT_bp_train_instr_BITS_15_TO_12_22_EQ_0b1001__ETC___d139 =
	     bp_train_instr[15:12] != 4'b1001 ||
	     bp_train_instr[11:7] == 5'd0 ||
	     bp_train_instr[6:2] != 5'd0 ||
	     bp_train_instr[1:0] != 2'b10 ;
  assign NOT_bp_train_instr_BITS_6_TO_0_15_EQ_0b1100111_ETC___d233 =
	     bp_train_instr[6:0] != 7'b1100111 &&
	     (bp_train_instr[6:0] != 7'h5B || bp_train_instr[14:12] != 3'h0 ||
	      bp_train_instr[31:25] != 7'h7F ||
	      bp_train_instr[24:20] != 5'h0C) ;
  assign NOT_predict_rsp_instr_BITS_11_TO_7_8_EQ_predic_ETC___d91 =
	     predict_rsp_instr[11:7] != predict_rsp_instr[19:15] ;
  assign _theResult_____1_fst__h8757 =
	     bp_train_cf_info[128] ?
	       _theResult_____1_fst__h8871 :
	       _theResult_____1_fst__h8913 ;
  assign _theResult_____1_fst__h8871 =
	     (rf_btb_fsms$D_OUT_1 == 2'b0) ?
	       bp_train_cf_info[127:64] :
	       bp_train_cf_info[63:0] ;
  assign _theResult_____1_snd_snd__h8759 =
	     bp_train_cf_info[128] ?
	       _theResult_____1_snd__h8872 :
	       _theResult_____1_snd__h8914 ;
  assign bp_train_instr_BITS_11_TO_7_25_EQ_bp_train_ins_ETC___d213 =
	     bp_train_instr[11:7] == bp_train_instr[19:15] ;
  assign bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d173 =
	     bp_train_instr[15:12] == 4'b1000 &&
	     bp_train_instr[11:7] != 5'd0 &&
	     bp_train_instr[6:2] == 5'd0 &&
	     bp_train_instr[1:0] == 2'b10 ;
  assign bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d216 =
	     bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_A_ETC___d173 ||
	     (bp_train_instr_BITS_15_TO_12_22_EQ_0b1001_35_A_ETC___d153 ?
		bp_train_instr[11:7] != 5'd1 :
		!bp_train_instr_BITS_11_TO_7_25_EQ_bp_train_ins_ETC___d213) ;
  assign bp_train_instr_BITS_15_TO_12_22_EQ_0b1000_23_O_ETC___d188 =
	     (bp_train_instr[15:12] == 4'b1000 ||
	      bp_train_instr[15:12] == 4'b1001) &&
	     bp_train_instr[11:7] != 5'd0 &&
	     bp_train_instr[6:2] == 5'd0 &&
	     bp_train_instr[1:0] == 2'b10 ;
  assign bp_train_instr_BITS_15_TO_12_22_EQ_0b1001_35_A_ETC___d153 =
	     bp_train_instr[15:12] == 4'b1001 &&
	     bp_train_instr[11:7] != 5'd0 &&
	     bp_train_instr[6:2] == 5'd0 &&
	     bp_train_instr[1:0] == 2'b10 ;
  assign bp_train_instr_BITS_6_TO_0_15_EQ_0b1100111_59__ETC___d170 =
	     bp_train_instr[6:0] == 7'b1100111 ||
	     bp_train_instr[6:0] == 7'h5B && bp_train_instr[14:12] == 3'h0 &&
	     bp_train_instr[31:25] == 7'h7F &&
	     bp_train_instr[24:20] == 5'h0C ;
  assign pred_pc___1__h3690 = { btb_bramcore2$DOA[62:0], 1'b0 } ;
  assign pred_pc__h2576 =
	     rg_pc + (predict_rsp_is_i32_not_i16 ? 64'd4 : 64'd2) ;
  assign predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d26 =
	     predict_rsp_instr[15:12] == 4'b1000 &&
	     predict_rsp_instr[11:7] != 5'd0 &&
	     predict_rsp_instr[6:2] == 5'd0 &&
	     predict_rsp_instr[1:0] == 2'b10 ;
  assign predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d93 =
	     predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1000_7__ETC___d26 ||
	     (predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1001_7__ETC___d30 ?
		predict_rsp_instr[11:7] != 5'd1 :
		NOT_predict_rsp_instr_BITS_11_TO_7_8_EQ_predic_ETC___d91) ;
  assign predict_rsp_instr_BITS_15_TO_12_6_EQ_0b1001_7__ETC___d30 =
	     predict_rsp_instr[15:12] == 4'b1001 &&
	     predict_rsp_instr[11:7] != 5'd0 &&
	     predict_rsp_instr[6:2] == 5'd0 &&
	     predict_rsp_instr[1:0] == 2'b10 ;
  assign predict_rsp_instr_BITS_6_TO_0_EQ_0b1100111_2_O_ETC___d63 =
	     predict_rsp_instr[6:0] == 7'b1100111 ||
	     predict_rsp_instr[6:0] == 7'h5B &&
	     predict_rsp_instr[14:12] == 3'h0 &&
	     predict_rsp_instr[31:25] == 7'h7F &&
	     predict_rsp_instr[24:20] == 5'h0C ;
  assign ret_pc___1__h4443 = bp_train_pc + 64'd2 ;
  assign ret_pc__h4404 = bp_train_pc + 64'd4 ;
  always@(rf_btb_fsms$D_OUT_1 or bp_train_cf_info)
  begin
    case (rf_btb_fsms$D_OUT_1)
      2'b0, 2'b01, 2'b10:
	  _theResult_____1_fst__h8913 = bp_train_cf_info[127:64];
      2'd3: _theResult_____1_fst__h8913 = bp_train_cf_info[63:0];
    endcase
  end
  always@(rf_btb_fsms$D_OUT_1)
  begin
    case (rf_btb_fsms$D_OUT_1)
      2'b0: _theResult_____1_snd__h8872 = 2'b01;
      2'b01: _theResult_____1_snd__h8872 = 2'b10;
      2'b10, 2'b11: _theResult_____1_snd__h8872 = 2'b11;
    endcase
  end
  always@(rf_btb_fsms$D_OUT_1)
  begin
    case (rf_btb_fsms$D_OUT_1)
      2'b0, 2'b01: _theResult_____1_snd__h8914 = 2'b0;
      2'b10: _theResult_____1_snd__h8914 = 2'b01;
      2'b11: _theResult_____1_snd__h8914 = 2'b10;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_index <= `BSV_ASSIGNMENT_DELAY 9'd0;
	rg_ras <= `BSV_ASSIGNMENT_DELAY
	    1040'h55555555555555552AAAAAAAAAAAAAAA95555555555555554AAAAAAAAAAAAAAAA55555555555555552AAAAAAAAAAAAAAA95555555555555554AAAAAAAAAAAAAAAA55555555555555552AAAAAAAAAAAAAAA95555555555555554AAAAAAAAAAAAAAAA55555555555555552AAAAAAAAAAAAAAA95555555555555554AAAAAAAAAAAAAAAA;
	rg_resetting <= `BSV_ASSIGNMENT_DELAY 1'd1;
      end
    else
      begin
        if (rg_index$EN) rg_index <= `BSV_ASSIGNMENT_DELAY rg_index$D_IN;
	if (rg_ras$EN) rg_ras <= `BSV_ASSIGNMENT_DELAY rg_ras$D_IN;
	if (rg_resetting$EN)
	  rg_resetting <= `BSV_ASSIGNMENT_DELAY rg_resetting$D_IN;
      end
    if (rg_pc$EN) rg_pc <= `BSV_ASSIGNMENT_DELAY rg_pc$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_index = 9'h0AA;
    rg_pc = 64'hAAAAAAAAAAAAAAAA;
    rg_ras =
	1040'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    rg_resetting = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkBranch_Predictor

