/*
 * Generated by Bluespec Compiler, version 2019.05.beta2 (build a88bf40db, 2019-05-24)
 * 
 * 
 * 
 */
#ifndef __vpi_wrapper_c_debug_client_response_send_h__
#define __vpi_wrapper_c_debug_client_response_send_h__

#include <vpi_user.h>

/* registration function */
void c_debug_client_response_send_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_debug_client_response_send_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_debug_client_response_send_h__ */
