/*
 * Generated by Bluespec Compiler, version 2019.05.beta2 (build a88bf40db, 2019-05-24)
 * 
 * 
 * 
 */
#ifndef __vpi_wrapper_c_get_symbol_val_h__
#define __vpi_wrapper_c_get_symbol_val_h__

#include <vpi_user.h>

/* registration function */
void c_get_symbol_val_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_get_symbol_val_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_get_symbol_val_h__ */
