name: Auto-assign issues to organization-level and repo projects

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_to_org_project:
    runs-on: ubuntu-latest
    name: Assign to organization project
    steps:
    - name: Assign NEW issues to organization project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        column_name : 'To Do'
        project: 'https://github.com/orgs/GaloisInc/projects/9'
  assign_to_repo_project:
    runs-on: ubuntu-latest
    name: Assign to repo project
    steps:
    - name: Assign NEW issues to organization project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:      
        project: 'https://github.com/GaloisInc/BESSPIN-CloudGFE/projects/1'
